### PR TITLE
Proper fix for 'mod' leaking across importlib tests

### PR DESCRIPTION
**Pull request by jaraco**
Addresses the [reported issue](https://github.com/python/cpython/pull/116307#issuecomment-1979699344):

```
 cpython ghpython-116307/safe-site-dir @ ./python.exe -m test test_importlib -v -m test_resolve -m test_module_resources
== CPython 3.13.0a3+ (heads/main:7fdd4235d7, Feb 6 2024, 12:06:21) [Clang 15.0.0 (clang-1500.1.0.2.5)]
== macOS-14.3.1-arm64-arm-64bit-Mach-O little-endian
== Python build: release
== cwd: /Users/jaraco/code/python/cpython/build/test_python_worker_67968æ
== CPU count: 12
== encodings: locale=UTF-8 FS=utf-8
== resources: all test resources are disabled, use -u option to unskip tests

Using random seed: 1092583257
0:00:00 load avg: 1.19 Run 1 test sequentially
0:00:00 load avg: 1.19 [1/1] test_importlib
test_module_resources (test.test_importlib.resources.test_files.ModulesFilesTests.test_module_resources)
A module can have resources found adjacent to the module. ... ok
test_resolve (test.test_importlib.test_main.ImportTests.test_resolve) ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.004s

OK

== Tests result: SUCCESS ==

1 test OK.

Total duration: 161 ms
Total tests: run=2 (filtered)
Total test files: run=1/1 (filtered)
Result: SUCCESS
```

### CODE REVIEW

**Comment by jaraco** [comment]
We'll want to decide if this can be backported to older Pythons or not. If you'd rather I propose this change directly to CPython, then you can rebase the other PR on this after merged.

**Review by erlend-aasland — APPROVED** [review]
Thanks; elegant!

**Comment by erlend-aasland** [comment]
I think it is fine to backport test.support stuff like this. We've done it before.

**Comment by jaraco** [comment]
I plan to submit these changes as a separate PR to CPython, as the re-import of importlib.resources now depends on it.

**Pull request merged**
